include 'GeometryObject.asm'
include 'Point/Point.asm'
include 'Segment/Segment.asm'
include 'CircleWithCenter/CircleWithCenter.asm'
include 'Line/Line.asm'
include 'Ellipse/Ellipse.asm'
include 'Polyline/Polyline.asm'
